INSERT INTO app_user(pk_user_id, email, password,reg_dt)
	VALUES(null, 'admin@email', (select MD5('administrator') from dual),
		(select sysdate() from dual));
INSERT INTO user_detail(pk_user_detail_id, first_name)
	VALUES(null, 'Administrator Account');
INSERT INTO AppUser_roles
	VALUES(1,'ROLE_USER'),(1,'ROLE_ADMIN');
INSERT INTO address(pk_address_id, post_addr1, state, fk_detail_id)
	VALUES(null, 'P O Box2361','gaborone', 1);
INSERT INTO menu(pk_menu_id, menu_type, menu_name, label,icon, admin_menu, menu_status, fk_menu_id)
	VALUES(1, 'HOME', 'vehicles', 'vehicles','car.png',0,1,null),
		(2, 'HOME', 'property', 'property','building.png',0,1,null),
		(3, 'HOME', 'pets','pets','paw-print.png',0,1,null),
		(4, 'HOME', 'Electronics', 'electronics','responsive.png',0,1,null),
		(5, 'HOME', 'home & garden', 'home&garden','outdoor-fence.png',0,1,null),
		(6, 'HOME', 'sports & leisure','sports&leisure','jet-ski.png',0,1,null),
		(7, 'HOME', 'cosmetics','cosmetics','cosmetics.png',0,1,null),
		(8, 'HOME', 'fashion','fashion','shirt.png',0,1,null),
		(9, 'HOME', 'travel','travel','bed.png',0,1,null),
		(10, 'HOME', 'jobs','jobs','briefcase.png',0,1,null),
		(11, 'HOME', 'events','events','concert.png',0,1,null),
		(12, 'HOME', 'services', 'services','settings.png',0,1,null),
		(13, 'SIDEBAR', 'home', 'home',null,0,1,null),
		(14, 'SIDEBAR', 'my account','account',null,0,1,null),
		(15, 'SIDEBAR', 'manage','manage',null,0,1,null),
		(16, 'SUBMENU', 'cars', 'cars', null,0,1, 1),
		(17, 'SUBMENU', 'motocycles', 'motocycles', null,0,1, 1),
		(18, 'SUBMENU', 'farm vehicles', 'farmvehicles', null,0,1, 1),
		(19, 'SUBMENU', 'auto parts', 'autoparts', null,0,1, 1),
		(20, 'SUBMENU', 'house for rent', 'houseforrent', null,0,1, 2),
		(21, 'SUBMENU', 'house to wanted', 'housetoshare', null,0,1, 2),
		(22, 'SUBMENU', 'house for sale', 'houseforsale', null,0,1, 2),
		(23, 'SUBMENU', 'commercial for sale', 'commercialforsale',null,0,1, 2),
		(24, 'SUBMENU', 'plot for sale', 'plotforsale', null,0,1, 2),
		(25, 'SUBMENU', 'cats', 'cats', null,0,1, 3),
		(26, 'SUBMENU', 'dogs', 'dogs', null,0,1, 3),
		(27, 'SUBMENU', 'pets lost & found', 'petslost&found', null,0,1, 3),
		(28, 'SUBMENU', 'free pets', 'free pets', null,0,1, 3),
		(29, 'SUBMENU', 'mobile phones', 'mobilephones', null,0,1, 4),
		(30, 'SUBMENU', 'phone accessories', 'phoneaccessories', null,0,1,4),
		(31, 'SUBMENU', 'tablets', 'tablets', null,0,1, 4),
		(33, 'SUBMENU', 'computers', 'computers', null,0,1, 4),
		(34, 'SUBMENU', 'TVs and radios', 'TVsandradios', null,0,1, 4),
		(35, 'SUBMENU', 'landscaping', 'landscaping', null,0,1, 5),
		(36, 'SUBMENU', 'appliances', 'appliances', null,0,1, 5),
		(37, 'SUBMENU', 'furniture', 'furniture', null,0,1, 5),
		(38, 'SUBMENU', 'antiques', 'antiques', null,0,1, 5),
		(39, 'SUBMENU', 'camping gear', 'campinggear',null,0,1, 6),
		(40, 'SUBMENU', 'tennis', 'tennis', null,0,1, 6),
		(41, 'SUBMENU', 'swimming', 'swimming', null,0,1, 6),
		(42, 'SUBMENU', 'books and games', 'booksandgames', null,0,1, 6),
		(43, 'SUBMENU', 'construction', 'construction', null,0,1, 12),
		(44, 'SUBMENU', 'pools and garden', 'poolsandgarden', null,0,1, 12),
		(45, 'SUBMENU', 'home maintenace', 'homemaitenance', null,0,1, 12),
		(46, 'SUBMENU', 'health and beauty', 'health and beauty', null,0,1, 12),
		(47, 'SUBMENU', 'dashboard', 'dashboard', null,0,1, 13),
		(48, 'SUBMENU','profile','profile', null,0,1, 14),
		(49, 'SUBMENU','preferences','preferences', null,0,1, 14),
		(50, 'SUBMENU','communication','communication', null,0,1, 14),
		(51, 'SUBMENU','activity', 'activity', null,1,1, 14),
		(52, 'SUBMENU','users', 'users', null,1,1, 15),
		(53, 'SUBMENU','menus', 'menus', null,1,1, 15),
		(54, 'SUBMENU','posts', 'posts', null,0,1, 15);
		
INSERT INTO advert(pk_advert_id, advert_status, submitted_date, fk_appuser_id, fk_menu_id)
	VALUES(1, 'SUBMITTED', (select sysdate() from dual), 1, (select pk_menu_id from menu where label='houseforrent')),
			(2, 'APPROVED', (select (sysdate()-10) from dual), 1,(select pk_menu_id from menu where label='autoparts')),
			(3, 'SUBMITTED', (select (sysdate()-3) from dual), 1, (select pk_menu_id from menu where label='cars')),
			(4, 'SUBMITTED', (select (sysdate()-1) from dual), 1, (select pk_menu_id from menu where label='cars')),
			(5, 'SUBMITTED', (select (sysdate()-18) from dual), 1,(select pk_menu_id from menu where label='furniture')),
			(6, 'REJECTED', (select (sysdate()-6) from dual), 1,(select pk_menu_id from menu where label='appliances')),
			(7, 'SUBMITTED', (select (sysdate()-14) from dual), 1,(select pk_menu_id from menu where label='houseforsale')),
			(8, 'APPROVED', (select (sysdate()-2) from dual), 1,(select pk_menu_id from menu where label='houseforrent')),
			(9, 'APPROVED', (select (sysdate()-5) from dual), 1,(select pk_menu_id from menu where label='houseforrent')),
			(10, 'SUBMITTED', (select (sysdate()-14) from dual), 1,(select pk_menu_id from menu where label='housetoshare')),
			(11, 'APPROVED', (select (sysdate()-8) from dual), 1,(select pk_menu_id from menu where label='mobilephones')),
			(12, 'SUBMITTED', (select (sysdate()-2) from dual), 1,(select pk_menu_id from menu where label='phoneaccessories')),
			(13, 'APPROVED', (select (sysdate()) from dual), 1,(select pk_menu_id from menu where label='computers')),
			(14, 'APPROVED', (select (sysdate()) from dual), 1,(select pk_menu_id from menu where label='cars')),
			(15, 'REJECTED', (select (sysdate()) from dual), 1,(select pk_menu_id from menu where label='pets'));

INSERT INTO advert_detail (pk_detail_id, body, contact_email, contact_phone, group_cdn, group_count, group_size, group_uuid, location, title, fk_advert_id) VALUES
(null, 'A LARGE ROOM- can be shared by 2 people porcelain floor tiles, ceiling,\r\n			multi res, boundary wall, electric fence, sliding gate, common toilet, & shower. Close to UB, IDM, \r\n			BAC, BCA, riverwalk, fairground, main mall.', NULL, '77100180', NULL, 0, NULL, NULL, 'Extension 14', 'house for rent',1),
(null, '2011 bmw120i with lots of extra Manual gear 150000km 80k Call 0813578313', NULL, '0813578313', NULL, 0, NULL, NULL, 'gaborone', '2011 bmw120i', 2),
(null, 'DUNLOP EXPRESS MOGODITSHANE Your Professional Tyre Fitment Centre Call 3938718 /3116423 App 71724544\r\n			Price valid till 30th September / Until stock last..', NULL, '3938718 /3116423', NULL, 0, NULL, NULL, 'Dunlop Express Mogoditshane', 'Tyres, Mag Wheels, Shocks, Brakes, Minor and major Services, Car Alarm, Car batteries, 3D Alignment', 3),
(null, 'GOLF POLO GTI MODEL 2013 DSG good condition.Low kilos 071kms.Full \r\n			serviced car.Aircon sound system.Price 130000 negotiable only serious buyer to view.Call 0814353868 /\r\n			0813040966 car in Dorado park', NULL, '0814353868 /0813040966', NULL, 0, NULL, NULL, 'mogoditshane', 'GOLF POLO GTI MODEL 2013', 4),
(null, 'Slumberland Concord Queen Mattress and Bed Combo Set Just Used for 1,5 Year by Diplomat R7,500 - \r\n			Gaborone Full Combo Set : 7500 BWP (Mattress 4000 BWP Bed 3000 Bwp, Sides 750 BWP )', NULL, ' ', NULL, 0, NULL, NULL, 'Gaborone', 'Slumberland Concord Queen Mattress and Bed Combo Set Just Used for 1,5 Year by Diplomat', 5),
(null, 'Fine Living Handheld Vacuum Cleaner. Plug in your \r\n			car lighter charger and clean around your car. Quick & Easy to use. Contacts: 74402139 P150.00', NULL, '74402139', NULL, 0, NULL, NULL, 'South East', 'Fine Living Handheld Car Vacuum Cleaners', 6),
(null, 'House for sale in Francistown Gerald 3 beds and 2 nd half \r\n			behind near GIPS and primary school Not fitted rooms Walled Power and water connected For 550k\r\n			Title deed For pic app 71273070', NULL, '71273070', NULL, 0, NULL, NULL, 'Francistown', 'House for sale in Francistown', 7),
(null, 'Compact 2 bedrooms in a multi res property in Tlokweng near Sefalana. \r\n			house is available first of October. 2,400-00 rent, 300-00 LEASE admin fee, and security deposit. \r\n			Call/whatsapp Ã£â‚¬â€¹ 76130462 Or inbox.', NULL, '76130462', NULL, 0, NULL, NULL, 'Tlokweng', 'Compact 2 bedrooms', 8),
(null, '3 bedroom bhc house available in Gaborone Phase2 on the 1st \r\n			October 2018. - kitchen has a fitted sink and a storeroom -bathroom has a bathtub and toilet, \r\n			-no landlord -Rent P3600 -security deposit P3600 Contact 71258149 or 76161232', NULL, '71258149/76161232', NULL, 0, NULL, NULL, 'phase 2', '3 bedroom bhc house for Rent', 9),
(null, 'M looking for a large room or 1 n half Even a Bachelor pad not above P1500.\r\n			Gabane,mogoditshane along route 4,tsolamosese,mmopane,metsimotlhabe.', NULL, ' ', NULL, 0, NULL, NULL, 'mogoditshane', 'room wanted', 10),
(null, '3month Samsung J1 Ace For Sale. P650 inclusive of headsets,protective \r\n			back cover and charger. Call or Text 71290199 if interested.', NULL, '71290199', NULL, 0, NULL, NULL, ' ', 'Samsung J1 Ace For Sale', 11),
(null, 'Head sets 25 pula Pouches 50 pula', NULL, ' ', NULL, 0, NULL, NULL, 'Broadhurst Industrial', 'Pouches for sale....clearance sale...J7 pro, iPhone 6s,J7, 7plus,J2 prime,J5 prime,J5', 12),
(null, 'i am selling a car in gaborone.', 'pearl@email', '71406569', null, 0, null, null, 'Gaborone', 'car for sale', 13),
(null, 'Dell Inspiron 5000 series i7 15.6" display HDMI', 'pearl@email', '71406569', null, 0, null, null, 'Gaborone', 'Dell laptop for sale', 14),
(null, 'English  Bulldogs  puppy''s.  KUSA retested  and inoculated  with vet card. 9 weeks  old and is ready for there new homes..', '', '0744994394 or 0621647175', null, 0, null, null, 'Gaborone', 'English bulldogs', 15);