INSERT INTO app_user(pk_user_id, email, password,reg_dt)
	VALUES(null, 'admin@email', 'administrator',(select sysdate() from dual));
INSERT INTO user_detail(pk_user_detail_id, first_name)
	VALUES(null, 'Administrator Account');
INSERT INTO AppUser_roles
	VALUES(1,'ROLE_USER'),(1,'ROLE_ADMIN');
INSERT INTO menu(pk_menu_id, menu_type, menu_name, label,icon, fk_menu_id)
	VALUES(1, 'HOME', 'vehicles', 'vehicles','ic_drive_eta_black_48dp.png',null),
		(2, 'HOME', 'property', 'property','ic_business_black_48dp.png',null),
		(3, 'HOME', 'pets','pets','ic_pets_black_48dp.png',null),
		(4, 'HOME', 'Electronics', 'electronics','ic_devices_black_48dp.png',null),
		(5, 'HOME', 'home & garden', 'home&garden','ic_weekend_black_48dp.png',null),
		(6, 'HOME', 'sports & leisure','sports&recreation','ic_pool_black_48dp.png',null),
		(7, 'HOME', 'services', 'services','ic_build_black_48dp.png',null),
		(8, 'SIDEBAR', 'home', 'home',null,null),
		(9, 'SIDEBAR', 'my account','account',null,null),
		(10, 'SIDEBAR', 'manage','manage',null,null),
		(null, 'SUBMENU', 'cars', 'cars', null, 1),
		(null, 'SUBMENU', 'motocycles', 'motocycles', null, 1),
		(null, 'SUBMENU', 'farm vehicles', 'farmvehicles', null, 1),
		(null, 'SUBMENU', 'auto parts', 'autoparts', null, 1),
		(null, 'SUBMENU', 'house for rent', 'houseforrent', null, 2),
		(null, 'SUBMENU', 'house to wanted', 'housetoshare', null, 2),
		(null, 'SUBMENU', 'commercial for sale', 'commercialforsale', null, 2),
		(null, 'SUBMENU', 'plot for sale', 'plotforsale', null, 2),
		(null, 'SUBMENU', 'cats', 'cats', null, 3),
		(null, 'SUBMENU', 'dogs', 'dogs', null, 3),
		(null, 'SUBMENU', 'pets lost & found', 'petslost&found', null, 3),
		(null, 'SUBMENU', 'free pets', 'free pets', null, 3),
		(null, 'SUBMENU', 'mobile phones', 'mobilephones', null, 4),
		(null, 'SUBMENU', 'tablets', 'tablets', null, 4),
		(null, 'SUBMENU', 'computers', 'computers', null, 4),
		(null, 'SUBMENU', 'TVs and radios', 'TVsandradios', null, 4),
		(null, 'SUBMENU', 'landscaping', 'landscaping', null, 5),
		(null, 'SUBMENU', 'appliances', 'appliances', null, 5),
		(null, 'SUBMENU', 'furniture', 'furniture', null, 5),
		(null, 'SUBMENU', 'antiques', 'antiques', null, 5),
		(null, 'SUBMENU', 'camping gear', 'campinggear', null, 6),
		(null, 'SUBMENU', 'tennis', 'tennis', null, 6),
		(null, 'SUBMENU', 'swimming', 'swimming', null, 6),
		(null, 'SUBMENU', 'books and games', 'booksandgames', null, 6),
		(null, 'SUBMENU', 'construction', 'construction', null, 7),
		(null, 'SUBMENU', 'pools and garden', 'poolsandgarden', null, 7),
		(null, 'SUBMENU', 'home maintenace', 'homemaitenance', null, 7),
		(null, 'SUBMENU', 'health and beauty', 'health and beauty', null, 7),
		(null, 'SUBMENU', 'dashboard', 'dashboard', null, 8),
		(null, 'SUBMENU','profile','profile', null, 9),
		(null, 'SUBMENU','preferences','preferences', null, 9),
		(null, 'SUBMENU','communication','communication', null, 9),
		(null, 'SUBMENU','activity', 'activity', null, 9),
		(null, 'SUBMENU','users', 'users', null, 10),
		(null, 'SUBMENU','menus', 'menus', null, 10),
		(null, 'SUBMENU','posts', 'posts', null, 10);
